version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive

  settings:
    revive:
      rules:
        - name: exported
          disabled: true

  exclusions:
    rules:
      - linters: [revive]
        text: "var-naming: avoid meaningless package names"
