# If tag not explicitly set, default to the git sha.
TAG ?= $(shell git rev-parse --short HEAD)
GitSHA = $(shell git rev-parse HEAD)
Date = $(shell date "+%Y-%m-%d %H:%M:%S")
RELEASE_VER ?= latest
LD_FLAGS = " \
    -X 'volcano.sh/resource-exporter/pkg/version.GitSHA=${GitSHA}' \
    -X 'volcano.sh/resource-exporter/pkg/version.Built=${Date}'   \
    -X 'volcano.sh/resource-exporter/pkg/version.Version=${RELEASE_VER}'"
